#!/bin/sh

echo "Creating directory ~/.myKeys"
#Create directories
mkdir -p ~/.myKeys/

echo "Generating keypair"
#Create Keys
openssl req -x509 -nodes -newkey rsa:2048 -keyout private-key.pem -out public-key.pem

echo "Moving the keys to the directory"
#Move keys to directory
mv private-key.pem ~/.myKeys/
mv public-key.pem ~/.myKeys/

echo "Done"
