#!/bin/sh

#Create directories
mkdir -p ~/.myKeys/

#Create Keys
openssl req -x509 -nodes -newkey rsa:2048 -keyout private-key.pem -out public-key.pem

#Move keys to directory
mv private-key.pem ~/.myKeys/
mv public-key.pem ~/.myKeys/
